# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcalc.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 463)
        MainWindow.setMinimumSize(QtCore.QSize(280, 463))
        MainWindow.setMaximumSize(QtCore.QSize(280, 463))
        MainWindow.setBaseSize(QtCore.QSize(280, 463))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 90, 71, 71))
        self.pushButton.setStyleSheet("background: #ccc; font-size: 20px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 90, 71, 71))
        self.pushButton_2.setStyleSheet("background: #ccc; font-size: 20px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 90, 71, 71))
        self.pushButton_3.setStyleSheet("background: #ccc; font-size: 20px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 160, 71, 71))
        self.pushButton_4.setStyleSheet("background: orange; font-size: 20px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 230, 71, 71))
        self.pushButton_5.setStyleSheet("background: orange; font-size: 20px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 300, 71, 71))
        self.pushButton_6.setStyleSheet("background: orange; font-size: 20px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(210, 370, 71, 71))
        self.pushButton_7.setStyleSheet("background: orange; font-size: 20px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 160, 71, 71))
        self.pushButton_8.setStyleSheet("font-size: 20px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 160, 71, 71))
        self.pushButton_9.setStyleSheet("font-size: 20px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(70, 160, 71, 71))
        self.pushButton_11.setStyleSheet("font-size: 20px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 230, 71, 71))
        self.pushButton_10.setStyleSheet("font-size: 20px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(140, 230, 71, 71))
        self.pushButton_12.setStyleSheet("font-size: 20px;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(70, 230, 71, 71))
        self.pushButton_13.setStyleSheet("font-size: 20px;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 300, 71, 71))
        self.pushButton_14.setStyleSheet("font-size: 20px;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(140, 300, 71, 71))
        self.pushButton_15.setStyleSheet("font-size: 20px;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(70, 300, 71, 71))
        self.pushButton_16.setStyleSheet("font-size: 20px;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 370, 141, 71))
        self.pushButton_17.setStyleSheet("font-size: 20px;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(140, 370, 71, 71))
        self.pushButton_18.setStyleSheet("font-size: 20px;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(210, 90, 71, 71))
        self.pushButton_19.setStyleSheet("background: orange; font-size: 20px;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 281, 91))
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setStyleSheet("font-size: 40px; padding-right: 15px; background: #E9DCCC; color: #000;")
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_12.raise_()
        self.pushButton_15.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_8.raise_()
        self.pushButton_11.raise_()
        self.pushButton_9.raise_()
        self.pushButton_13.raise_()
        self.pushButton_10.raise_()
        self.pushButton_16.raise_()
        self.pushButton_14.raise_()
        self.pushButton_19.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_QT = QtWidgets.QAction(MainWindow)
        self.actionAbout_QT.setObjectName("actionAbout_QT")
        self.actionAbout_QtCalc = QtWidgets.QAction(MainWindow)
        self.actionAbout_QtCalc.setObjectName("actionAbout_QtCalc")
        self.menuHelp.addAction(self.actionAbout_QT)
        self.menuHelp.addAction(self.actionAbout_QtCalc)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtCalc"))
        self.pushButton.setText(_translate("MainWindow", "AC"))
        self.pushButton_2.setText(_translate("MainWindow", "±"))
        self.pushButton_3.setText(_translate("MainWindow", "%"))
        self.pushButton_4.setText(_translate("MainWindow", "x"))
        self.pushButton_5.setText(_translate("MainWindow", "–"))
        self.pushButton_6.setText(_translate("MainWindow", "+"))
        self.pushButton_7.setText(_translate("MainWindow", "="))
        self.pushButton_8.setText(_translate("MainWindow", "9"))
        self.pushButton_9.setText(_translate("MainWindow", "7"))
        self.pushButton_11.setText(_translate("MainWindow", "8"))
        self.pushButton_10.setText(_translate("MainWindow", "4"))
        self.pushButton_12.setText(_translate("MainWindow", "6"))
        self.pushButton_13.setText(_translate("MainWindow", "5"))
        self.pushButton_14.setText(_translate("MainWindow", "1"))
        self.pushButton_15.setText(_translate("MainWindow", "3"))
        self.pushButton_16.setText(_translate("MainWindow", "2"))
        self.pushButton_17.setText(_translate("MainWindow", "0"))
        self.pushButton_18.setText(_translate("MainWindow", "."))
        self.pushButton_19.setText(_translate("MainWindow", "÷"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_QT.setText(_translate("MainWindow", "About QT"))
        self.actionAbout_QtCalc.setText(_translate("MainWindow", "About QtCalc"))
